# Site settings
title: anti-intelligence
email: anti-intelligence@gmail.com
description: Work of Kevin Rogan
root: /ai
url: 'http://anti-intelligence.github.io' # the base hostname & protocol for your site
twitter_username: kvnrogan

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
