# Site settings
title: anti-intelligence
email: anti-intelligence@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Work of Kevin Rogan
resource: https://anti-intelligence.github.io/ai
baseurl: '/ai' # the subpath of your site, e.g. /blog/
url: 'http://anti-intelligence.github.io' # the base hostname & protocol for your site
twitter_username: kvnrogan

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
