# Site settings
title: anti-intelligence
email: anti-intelligence@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Work of Kevin Rogan
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://localhost:4000' # the base hostname & protocol for your site
twitter_username: kvnrogan
github_username: jekyll

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
